### ISSUE TITLE
Open to non-regex line-by-line features?

### ISSUE THREAD

**Issue by mplewis** [marklarr/mayday#16]
Hey @marklarr, thanks for Mayday. Everyone at work is loving it ;)

I was wondering if you would be open to adding line-by-line warnings and errors that are easier to use than regex, like:

```ruby
# Throws a warning when "// Copyright (c)" is found on any line in a file
error_present "// Copyright (c)"
```

The copyright boilerplate, TODO, and FIXME are three cases in which I'd love to add a really quick warning or error but don't want to make sure my regex is correct. What do you think?

**Comment by marklarr** [comment]
I would just suggest doing something like

```ruby
error :line { |line| line.include?("// Copyright (c)") }`
```

:smiley:

**Comment by mplewis** [comment]
Now that I think about it you could probably just bring in [Regexp::escape](http://ruby-doc.org/core-2.2.0/Regexp.html#method-c-escape) to do that for you. Thanks for the suggestions!

**Comment by marklarr** [comment]
Good thinking!
