### ISSUE TITLE
Mayday seriously broken w/ Xcode 6.3 (running mayday causes Xcode crash)

### ISSUE THREAD

**Issue by zbeckman** [marklarr/mayday#17]
We love Mayday. Very much hoping you are still maintaining it...

After 6.3 update, Xcode instantly crashes upon running Mayday. Also, no warnings are showing up in the build.

506 zbeckman:Glimpulse$ mayday
Integrating mayday into your project...
Done!
// And... Xcode crashes :-(

**Comment by marklarr** [comment]
I'm really sorry for getting to those so late. I'll take a look into this tomorrow.

**Comment by marklarr** [comment]
Well, this is embarrassing -- my machine is still on 10.9, because I hate change (ha) and I've been working mainly on Ruby for a while now. As a result, I can't update to Xcode 6.3.

@zbeckman can you check if the latest Mayday release works for you? (0.1.2)

**Comment by zbeckman** [comment]
Seems to be working pretty well – we're on Xcode 7 now (beta), as well. No crashes here either, at least that I've seen so far.
